version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  robotsmeta:
    in: .
  httpheader:
    in: httpheader/**
  htmlmeta:
    in: htmlmeta/**

vendors:
  nethtml:
    in:
      - golang.org/x/net/html
      - golang.org/x/net/html/**

deps:
  httpheader:
    mayDependOn:
      - robotsmeta
  htmlmeta:
    mayDependOn:
      - robotsmeta
    canUse:
      - nethtml

excludeFiles:
  - "_test\\.go"
