version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  scrapedpage:
    in: .

deps:
  scrapedpage:
    canUse:
      - canonicalurl
      - pagefetch
      - scraperequestcontract

vendors:
  canonicalurl:
    in: github.com/nikitakarpei/yacy-rwi-node/canonicalurl
  pagefetch:
    in: github.com/nikitakarpei/yacy-rwi-node/pagefetch
  scraperequestcontract:
    in: github.com/nikitakarpei/yacy-rwi-node/scraperequestcontract

excludeFiles:
  - "_test\\.go"
