version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errname
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wrapcheck
  exclusions:
    generated: strict

formatters:
  enable:
    - gofumpt
    - gci
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    golines:
      max-len: 100
