version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errname
    - errorlint
    - funlen
    - gocritic
    - gocognit
    - gosec
    - iface
    - interfacebloat
    - loggercheck
    - maintidx
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - sloglint
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wrapcheck
  settings:
    funlen:
      lines: 80
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gosec:
      excludes:
        - G401
        - G501
    maintidx:
      under: 20
    revive:
      rules:
        - name: argument-limit
          arguments:
            - 5
        - name: cognitive-complexity
          arguments:
            - 20
        - name: function-length
          arguments:
            - 50
            - 80
    wrapcheck:
      ignore-package-globs:
        - github.com/nikitakarpei/yacy-rwi-node/*
        - golang.org/x/sync/errgroup
    sloglint:
      attr-only: true
      context: all
      key-naming-case: camel
      static-msg: true
  exclusions:
    generated: strict

formatters:
  enable:
    - gofumpt
    - gci
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/nikitakarpei/yacy-rwi-node)
    golines:
      max-len: 100
