version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  yacycrawlcontract:
    in:
      - .
      - "**"

vendors:
  yacymodel:
    in:
      - github.com/nikitakarpei/yacy-rwi-node/yacymodel
      - github.com/nikitakarpei/yacy-rwi-node/yacymodel/**

deps:
  yacycrawlcontract:
    canUse:
      - yacymodel

excludeFiles:
  - "_test\.go"
