version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  pagelinks:
    in: .

vendors:
  canonicalurl:
    in:
      - github.com/nikitakarpei/yacy-rwi-node/canonicalurl
      - github.com/nikitakarpei/yacy-rwi-node/canonicalurl/**
  xnet:
    in:
      - golang.org/x/net/**

deps:
  pagelinks:
    canUse:
      - canonicalurl
      - xnet

excludeFiles:
  - "_test\\.go"
