# syntax=docker/dockerfile:1

FROM busybox:1.36.1-uclibc@sha256:0872fb3a7632ba9d0ae46a8e832a62b30ce83a6f220b8bb52903d9cf477dabe3

COPY crawled_text_search.py /payload/crawled_text_search.py

ENTRYPOINT ["cp"]
