version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  documentextraction:
    in: .
  htmltree:
    in: bodies/htmltree/**

vendors:
  canonicalurl:
    in:
      - github.com/nikitakarpei/yacy-rwi-node/canonicalurl
      - github.com/nikitakarpei/yacy-rwi-node/canonicalurl/**
  xnet:
    in:
      - golang.org/x/net/**

deps:
  documentextraction:
    mayDependOn:
      - htmltree
    canUse:
      - canonicalurl
      - xnet
  htmltree:
    canUse:
      - xnet

excludeFiles:
  - "_test\\.go"
