version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  pagemarkdownstore:
    in:
      - .
      - "**"

vendors:
  nats:
    in:
      - github.com/nats-io/nats.go
      - github.com/nats-io/nats.go/**

deps:
  pagemarkdownstore:
    canUse:
      - nats

excludeFiles:
  - "_test\.go"
