version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  pebblevault:
    in:
      - .
      - "**"

vendors:
  vault:
    in: github.com/nikitakarpei/yacy-rwi-node/vault
  pebble:
    in:
      - github.com/cockroachdb/pebble/v2
      - github.com/cockroachdb/pebble/v2/bloom

deps:
  pebblevault:
    canUse:
      - vault
      - pebble

excludeFiles:
  - "_test\\.go"
