// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: crawler/v1/crawloutcomes.proto

package crawlerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrawlOutcomes_ReadPage_FullMethodName = "/crawler.v1.CrawlOutcomes/ReadPage"
)

// CrawlOutcomesClient is the client API for CrawlOutcomes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrawlOutcomes yields what crawling last did with a URL.
type CrawlOutcomesClient interface {
	// ReadPage answers INVALID_ARGUMENT for a URL that cannot be canonicalized.
	ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*PageOutcome, error)
}

type crawlOutcomesClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlOutcomesClient(cc grpc.ClientConnInterface) CrawlOutcomesClient {
	return &crawlOutcomesClient{cc}
}

func (c *crawlOutcomesClient) ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*PageOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageOutcome)
	err := c.cc.Invoke(ctx, CrawlOutcomes_ReadPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlOutcomesServer is the server API for CrawlOutcomes service.
// All implementations must embed UnimplementedCrawlOutcomesServer
// for forward compatibility.
//
// CrawlOutcomes yields what crawling last did with a URL.
type CrawlOutcomesServer interface {
	// ReadPage answers INVALID_ARGUMENT for a URL that cannot be canonicalized.
	ReadPage(context.Context, *ReadPageRequest) (*PageOutcome, error)
	mustEmbedUnimplementedCrawlOutcomesServer()
}

// UnimplementedCrawlOutcomesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrawlOutcomesServer struct{}

func (UnimplementedCrawlOutcomesServer) ReadPage(context.Context, *ReadPageRequest) (*PageOutcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPage not implemented")
}
func (UnimplementedCrawlOutcomesServer) mustEmbedUnimplementedCrawlOutcomesServer() {}
func (UnimplementedCrawlOutcomesServer) testEmbeddedByValue()                       {}

// UnsafeCrawlOutcomesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlOutcomesServer will
// result in compilation errors.
type UnsafeCrawlOutcomesServer interface {
	mustEmbedUnimplementedCrawlOutcomesServer()
}

func RegisterCrawlOutcomesServer(s grpc.ServiceRegistrar, srv CrawlOutcomesServer) {
	// If the following call pancis, it indicates UnimplementedCrawlOutcomesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrawlOutcomes_ServiceDesc, srv)
}

func _CrawlOutcomes_ReadPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlOutcomesServer).ReadPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlOutcomes_ReadPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlOutcomesServer).ReadPage(ctx, req.(*ReadPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlOutcomes_ServiceDesc is the grpc.ServiceDesc for CrawlOutcomes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlOutcomes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.v1.CrawlOutcomes",
	HandlerType: (*CrawlOutcomesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPage",
			Handler:    _CrawlOutcomes_ReadPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler/v1/crawloutcomes.proto",
}
