// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: crawler/v1/crawloutcomes.proto

package crawlerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPageRequest) Reset() {
	*x = ReadPageRequest{}
	mi := &file_crawler_v1_crawloutcomes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPageRequest) ProtoMessage() {}

func (x *ReadPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_v1_crawloutcomes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPageRequest.ProtoReflect.Descriptor instead.
func (*ReadPageRequest) Descriptor() ([]byte, []int) {
	return file_crawler_v1_crawloutcomes_proto_rawDescGZIP(), []int{0}
}

func (x *ReadPageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PageOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The canonical form of the requested URL.
	CanonicalUrl string `protobuf:"bytes,1,opt,name=canonical_url,json=canonicalUrl,proto3" json:"canonical_url,omitempty"`
	// Where crawling resolved the URL to, the canonical URL itself when no redirect
	// was recorded.
	ResolvedUrl string `protobuf:"bytes,2,opt,name=resolved_url,json=resolvedUrl,proto3" json:"resolved_url,omitempty"`
	// Absent while the URL is not disposed.
	Disposal      *PageDisposal `protobuf:"bytes,3,opt,name=disposal,proto3" json:"disposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageOutcome) Reset() {
	*x = PageOutcome{}
	mi := &file_crawler_v1_crawloutcomes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageOutcome) ProtoMessage() {}

func (x *PageOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_v1_crawloutcomes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageOutcome.ProtoReflect.Descriptor instead.
func (*PageOutcome) Descriptor() ([]byte, []int) {
	return file_crawler_v1_crawloutcomes_proto_rawDescGZIP(), []int{1}
}

func (x *PageOutcome) GetCanonicalUrl() string {
	if x != nil {
		return x.CanonicalUrl
	}
	return ""
}

func (x *PageOutcome) GetResolvedUrl() string {
	if x != nil {
		return x.ResolvedUrl
	}
	return ""
}

func (x *PageOutcome) GetDisposal() *PageDisposal {
	if x != nil {
		return x.Disposal
	}
	return nil
}

type PageDisposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Changes each time the URL is disposed again. A caller captures the mark before it
	// places an order and compares it while it waits, to tell a new disposal from an old one.
	Mark          string `protobuf:"bytes,1,opt,name=mark,proto3" json:"mark,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageDisposal) Reset() {
	*x = PageDisposal{}
	mi := &file_crawler_v1_crawloutcomes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageDisposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageDisposal) ProtoMessage() {}

func (x *PageDisposal) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_v1_crawloutcomes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageDisposal.ProtoReflect.Descriptor instead.
func (*PageDisposal) Descriptor() ([]byte, []int) {
	return file_crawler_v1_crawloutcomes_proto_rawDescGZIP(), []int{2}
}

func (x *PageDisposal) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *PageDisposal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_crawler_v1_crawloutcomes_proto protoreflect.FileDescriptor

const file_crawler_v1_crawloutcomes_proto_rawDesc = "" +
	"\n" +
	"\x1ecrawler/v1/crawloutcomes.proto\x12\n" +
	"crawler.v1\"#\n" +
	"\x0fReadPageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8b\x01\n" +
	"\vPageOutcome\x12#\n" +
	"\rcanonical_url\x18\x01 \x01(\tR\fcanonicalUrl\x12!\n" +
	"\fresolved_url\x18\x02 \x01(\tR\vresolvedUrl\x124\n" +
	"\bdisposal\x18\x03 \x01(\v2\x18.crawler.v1.PageDisposalR\bdisposal\":\n" +
	"\fPageDisposal\x12\x12\n" +
	"\x04mark\x18\x01 \x01(\tR\x04mark\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2Q\n" +
	"\rCrawlOutcomes\x12@\n" +
	"\bReadPage\x12\x1b.crawler.v1.ReadPageRequest\x1a\x17.crawler.v1.PageOutcomeBNZLgithub.com/nikitakarpei/yacy-rwi-node/yacycrawlcontract/crawler/v1;crawlerv1b\x06proto3"

var (
	file_crawler_v1_crawloutcomes_proto_rawDescOnce sync.Once
	file_crawler_v1_crawloutcomes_proto_rawDescData []byte
)

func file_crawler_v1_crawloutcomes_proto_rawDescGZIP() []byte {
	file_crawler_v1_crawloutcomes_proto_rawDescOnce.Do(func() {
		file_crawler_v1_crawloutcomes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crawler_v1_crawloutcomes_proto_rawDesc), len(file_crawler_v1_crawloutcomes_proto_rawDesc)))
	})
	return file_crawler_v1_crawloutcomes_proto_rawDescData
}

var file_crawler_v1_crawloutcomes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crawler_v1_crawloutcomes_proto_goTypes = []any{
	(*ReadPageRequest)(nil), // 0: crawler.v1.ReadPageRequest
	(*PageOutcome)(nil),     // 1: crawler.v1.PageOutcome
	(*PageDisposal)(nil),    // 2: crawler.v1.PageDisposal
}
var file_crawler_v1_crawloutcomes_proto_depIdxs = []int32{
	2, // 0: crawler.v1.PageOutcome.disposal:type_name -> crawler.v1.PageDisposal
	0, // 1: crawler.v1.CrawlOutcomes.ReadPage:input_type -> crawler.v1.ReadPageRequest
	1, // 2: crawler.v1.CrawlOutcomes.ReadPage:output_type -> crawler.v1.PageOutcome
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_crawler_v1_crawloutcomes_proto_init() }
func file_crawler_v1_crawloutcomes_proto_init() {
	if File_crawler_v1_crawloutcomes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crawler_v1_crawloutcomes_proto_rawDesc), len(file_crawler_v1_crawloutcomes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crawler_v1_crawloutcomes_proto_goTypes,
		DependencyIndexes: file_crawler_v1_crawloutcomes_proto_depIdxs,
		MessageInfos:      file_crawler_v1_crawloutcomes_proto_msgTypes,
	}.Build()
	File_crawler_v1_crawloutcomes_proto = out.File
	file_crawler_v1_crawloutcomes_proto_goTypes = nil
	file_crawler_v1_crawloutcomes_proto_depIdxs = nil
}
