version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  memoryvault:
    in:
      - .
      - "**"

vendors:
  vault:
    in: github.com/nikitakarpei/yacy-rwi-node/vault

deps:
  memoryvault:
    canUse:
      - vault

excludeFiles:
  - "_test\\.go"
