version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  pagemarkdownstore:
    in:
      - .
      - "**"

vendors:
  yacycrawlcontract:
    in:
      - github.com/nikitakarpei/yacy-rwi-node/yacycrawlcontract
      - github.com/nikitakarpei/yacy-rwi-node/yacycrawlcontract/**
  canonicalurl:
    in:
      - github.com/nikitakarpei/yacy-rwi-node/canonicalurl
      - github.com/nikitakarpei/yacy-rwi-node/canonicalurl/**
  grpc:
    in:
      - google.golang.org/grpc
      - google.golang.org/grpc/**
  protobuf:
    in:
      - google.golang.org/protobuf
      - google.golang.org/protobuf/**

deps:
  pagemarkdownstore:
    mayDependOn:
      - pagemarkdownstore
    canUse:
      - yacycrawlcontract
      - canonicalurl
      - grpc
      - protobuf

excludeFiles:
  - "_test\\.go"
