version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  scraperequestcontract:
    in: .

deps:
  scraperequestcontract:
    canUse:
      - canonicalurl

vendors:
  canonicalurl:
    in: github.com/nikitakarpei/yacy-rwi-node/canonicalurl

excludeFiles:
  - "_test\\.go"
