http_port 3128

cache_peer renderproxy parent 8080 0 no-query no-digest no-netdb-exchange default
never_direct allow all
positive_dns_ttl 30 seconds
pinger_enable off

http_access allow all

collapsed_forwarding on

cache_mem 64 MB
maximum_object_size 16 MB
cache_dir ufs /var/spool/squid 1024 16 256

access_log stdio:/dev/stdout
cache_log stdio:/dev/stdout
