// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: corpusmarkdown/v1/markdowncorpus.proto

package corpusmarkdownv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarkdownCorpus_RecallPage_FullMethodName = "/corpusmarkdown.v1.MarkdownCorpus/RecallPage"
)

// MarkdownCorpusClient is the client API for MarkdownCorpus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarkdownCorpus yields the markdown an operator's own corpus holds for a page.
type MarkdownCorpusClient interface {
	// RecallPage answers NOT_FOUND for a URL the corpus does not hold.
	RecallPage(ctx context.Context, in *RecallPageRequest, opts ...grpc.CallOption) (*RecallPageResponse, error)
}

type markdownCorpusClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkdownCorpusClient(cc grpc.ClientConnInterface) MarkdownCorpusClient {
	return &markdownCorpusClient{cc}
}

func (c *markdownCorpusClient) RecallPage(ctx context.Context, in *RecallPageRequest, opts ...grpc.CallOption) (*RecallPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallPageResponse)
	err := c.cc.Invoke(ctx, MarkdownCorpus_RecallPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkdownCorpusServer is the server API for MarkdownCorpus service.
// All implementations must embed UnimplementedMarkdownCorpusServer
// for forward compatibility.
//
// MarkdownCorpus yields the markdown an operator's own corpus holds for a page.
type MarkdownCorpusServer interface {
	// RecallPage answers NOT_FOUND for a URL the corpus does not hold.
	RecallPage(context.Context, *RecallPageRequest) (*RecallPageResponse, error)
	mustEmbedUnimplementedMarkdownCorpusServer()
}

// UnimplementedMarkdownCorpusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarkdownCorpusServer struct{}

func (UnimplementedMarkdownCorpusServer) RecallPage(context.Context, *RecallPageRequest) (*RecallPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecallPage not implemented")
}
func (UnimplementedMarkdownCorpusServer) mustEmbedUnimplementedMarkdownCorpusServer() {}
func (UnimplementedMarkdownCorpusServer) testEmbeddedByValue()                        {}

// UnsafeMarkdownCorpusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkdownCorpusServer will
// result in compilation errors.
type UnsafeMarkdownCorpusServer interface {
	mustEmbedUnimplementedMarkdownCorpusServer()
}

func RegisterMarkdownCorpusServer(s grpc.ServiceRegistrar, srv MarkdownCorpusServer) {
	// If the following call pancis, it indicates UnimplementedMarkdownCorpusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarkdownCorpus_ServiceDesc, srv)
}

func _MarkdownCorpus_RecallPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownCorpusServer).RecallPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkdownCorpus_RecallPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownCorpusServer).RecallPage(ctx, req.(*RecallPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkdownCorpus_ServiceDesc is the grpc.ServiceDesc for MarkdownCorpus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkdownCorpus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corpusmarkdown.v1.MarkdownCorpus",
	HandlerType: (*MarkdownCorpusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecallPage",
			Handler:    _MarkdownCorpus_RecallPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "corpusmarkdown/v1/markdowncorpus.proto",
}
