// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: corpusmarkdown/v1/markdowncorpus.proto

package corpusmarkdownv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecallPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallPageRequest) Reset() {
	*x = RecallPageRequest{}
	mi := &file_corpusmarkdown_v1_markdowncorpus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallPageRequest) ProtoMessage() {}

func (x *RecallPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corpusmarkdown_v1_markdowncorpus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallPageRequest.ProtoReflect.Descriptor instead.
func (*RecallPageRequest) Descriptor() ([]byte, []int) {
	return file_corpusmarkdown_v1_markdowncorpus_proto_rawDescGZIP(), []int{0}
}

func (x *RecallPageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RecallPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanonicalUrl  string                 `protobuf:"bytes,1,opt,name=canonical_url,json=canonicalUrl,proto3" json:"canonical_url,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallPageResponse) Reset() {
	*x = RecallPageResponse{}
	mi := &file_corpusmarkdown_v1_markdowncorpus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallPageResponse) ProtoMessage() {}

func (x *RecallPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corpusmarkdown_v1_markdowncorpus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallPageResponse.ProtoReflect.Descriptor instead.
func (*RecallPageResponse) Descriptor() ([]byte, []int) {
	return file_corpusmarkdown_v1_markdowncorpus_proto_rawDescGZIP(), []int{1}
}

func (x *RecallPageResponse) GetCanonicalUrl() string {
	if x != nil {
		return x.CanonicalUrl
	}
	return ""
}

func (x *RecallPageResponse) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

var File_corpusmarkdown_v1_markdowncorpus_proto protoreflect.FileDescriptor

const file_corpusmarkdown_v1_markdowncorpus_proto_rawDesc = "" +
	"\n" +
	"&corpusmarkdown/v1/markdowncorpus.proto\x12\x11corpusmarkdown.v1\"%\n" +
	"\x11RecallPageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"U\n" +
	"\x12RecallPageResponse\x12#\n" +
	"\rcanonical_url\x18\x01 \x01(\tR\fcanonicalUrl\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown2k\n" +
	"\x0eMarkdownCorpus\x12Y\n" +
	"\n" +
	"RecallPage\x12$.corpusmarkdown.v1.RecallPageRequest\x1a%.corpusmarkdown.v1.RecallPageResponseB\\ZZgithub.com/nikitakarpei/yacy-rwi-node/pagemarkdownstore/corpusmarkdown/v1;corpusmarkdownv1b\x06proto3"

var (
	file_corpusmarkdown_v1_markdowncorpus_proto_rawDescOnce sync.Once
	file_corpusmarkdown_v1_markdowncorpus_proto_rawDescData []byte
)

func file_corpusmarkdown_v1_markdowncorpus_proto_rawDescGZIP() []byte {
	file_corpusmarkdown_v1_markdowncorpus_proto_rawDescOnce.Do(func() {
		file_corpusmarkdown_v1_markdowncorpus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corpusmarkdown_v1_markdowncorpus_proto_rawDesc), len(file_corpusmarkdown_v1_markdowncorpus_proto_rawDesc)))
	})
	return file_corpusmarkdown_v1_markdowncorpus_proto_rawDescData
}

var file_corpusmarkdown_v1_markdowncorpus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_corpusmarkdown_v1_markdowncorpus_proto_goTypes = []any{
	(*RecallPageRequest)(nil),  // 0: corpusmarkdown.v1.RecallPageRequest
	(*RecallPageResponse)(nil), // 1: corpusmarkdown.v1.RecallPageResponse
}
var file_corpusmarkdown_v1_markdowncorpus_proto_depIdxs = []int32{
	0, // 0: corpusmarkdown.v1.MarkdownCorpus.RecallPage:input_type -> corpusmarkdown.v1.RecallPageRequest
	1, // 1: corpusmarkdown.v1.MarkdownCorpus.RecallPage:output_type -> corpusmarkdown.v1.RecallPageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_corpusmarkdown_v1_markdowncorpus_proto_init() }
func file_corpusmarkdown_v1_markdowncorpus_proto_init() {
	if File_corpusmarkdown_v1_markdowncorpus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corpusmarkdown_v1_markdowncorpus_proto_rawDesc), len(file_corpusmarkdown_v1_markdowncorpus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corpusmarkdown_v1_markdowncorpus_proto_goTypes,
		DependencyIndexes: file_corpusmarkdown_v1_markdowncorpus_proto_depIdxs,
		MessageInfos:      file_corpusmarkdown_v1_markdowncorpus_proto_msgTypes,
	}.Build()
	File_corpusmarkdown_v1_markdowncorpus_proto = out.File
	file_corpusmarkdown_v1_markdowncorpus_proto_goTypes = nil
	file_corpusmarkdown_v1_markdowncorpus_proto_depIdxs = nil
}
