#!/bin/sh
set -eu

module=$(${GO:-go} list -m)

pattern=$(
	{
		printf '/main\\.go:\n'
		find . -mindepth 1 -type d -exec test -e '{}/go.mod' ';' -prune \
			-o -name .covignore -print |
			sed 's|^\./||; s|\.covignore$||' |
			while read -r dir; do
				printf '%s/%s\n' "$module" "$dir"
			done
	} | paste -sd'|' -
)

printf '%s\n' "$pattern"
