// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: corpusrecall/v1/recall.proto

package corpusrecallv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RepresentationKind names a corpus representation of a page.
type RepresentationKind int32

const (
	RepresentationKind_REPRESENTATION_KIND_UNSPECIFIED RepresentationKind = 0
	RepresentationKind_REPRESENTATION_KIND_MARKDOWN    RepresentationKind = 1
	RepresentationKind_REPRESENTATION_KIND_TEXT        RepresentationKind = 2
)

// Enum value maps for RepresentationKind.
var (
	RepresentationKind_name = map[int32]string{
		0: "REPRESENTATION_KIND_UNSPECIFIED",
		1: "REPRESENTATION_KIND_MARKDOWN",
		2: "REPRESENTATION_KIND_TEXT",
	}
	RepresentationKind_value = map[string]int32{
		"REPRESENTATION_KIND_UNSPECIFIED": 0,
		"REPRESENTATION_KIND_MARKDOWN":    1,
		"REPRESENTATION_KIND_TEXT":        2,
	}
)

func (x RepresentationKind) Enum() *RepresentationKind {
	p := new(RepresentationKind)
	*p = x
	return p
}

func (x RepresentationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepresentationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_corpusrecall_v1_recall_proto_enumTypes[0].Descriptor()
}

func (RepresentationKind) Type() protoreflect.EnumType {
	return &file_corpusrecall_v1_recall_proto_enumTypes[0]
}

func (x RepresentationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepresentationKind.Descriptor instead.
func (RepresentationKind) EnumDescriptor() ([]byte, []int) {
	return file_corpusrecall_v1_recall_proto_rawDescGZIP(), []int{0}
}

type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Kinds         []RepresentationKind   `protobuf:"varint,2,rep,packed,name=kinds,proto3,enum=corpusrecall.v1.RepresentationKind" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_corpusrecall_v1_recall_proto_rawDescGZIP(), []int{0}
}

func (x *RecallRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RecallRequest) GetKinds() []RepresentationKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// MarkdownRepresentation is a page rendered as markdown.
type MarkdownRepresentation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanonicalUrl  string                 `protobuf:"bytes,1,opt,name=canonical_url,json=canonicalUrl,proto3" json:"canonical_url,omitempty"`
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkdownRepresentation) Reset() {
	*x = MarkdownRepresentation{}
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkdownRepresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkdownRepresentation) ProtoMessage() {}

func (x *MarkdownRepresentation) ProtoReflect() protoreflect.Message {
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkdownRepresentation.ProtoReflect.Descriptor instead.
func (*MarkdownRepresentation) Descriptor() ([]byte, []int) {
	return file_corpusrecall_v1_recall_proto_rawDescGZIP(), []int{1}
}

func (x *MarkdownRepresentation) GetCanonicalUrl() string {
	if x != nil {
		return x.CanonicalUrl
	}
	return ""
}

func (x *MarkdownRepresentation) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

// TextRepresentation is a page's extracted plain text with its metadata.
type TextRepresentation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanonicalUrl  string                 `protobuf:"bytes,1,opt,name=canonical_url,json=canonicalUrl,proto3" json:"canonical_url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRepresentation) Reset() {
	*x = TextRepresentation{}
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRepresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRepresentation) ProtoMessage() {}

func (x *TextRepresentation) ProtoReflect() protoreflect.Message {
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRepresentation.ProtoReflect.Descriptor instead.
func (*TextRepresentation) Descriptor() ([]byte, []int) {
	return file_corpusrecall_v1_recall_proto_rawDescGZIP(), []int{2}
}

func (x *TextRepresentation) GetCanonicalUrl() string {
	if x != nil {
		return x.CanonicalUrl
	}
	return ""
}

func (x *TextRepresentation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TextRepresentation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextRepresentation) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Representation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Representation:
	//
	//	*Representation_Markdown
	//	*Representation_Text
	Representation isRepresentation_Representation `protobuf_oneof:"representation"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Representation) Reset() {
	*x = Representation{}
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Representation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Representation) ProtoMessage() {}

func (x *Representation) ProtoReflect() protoreflect.Message {
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Representation.ProtoReflect.Descriptor instead.
func (*Representation) Descriptor() ([]byte, []int) {
	return file_corpusrecall_v1_recall_proto_rawDescGZIP(), []int{3}
}

func (x *Representation) GetRepresentation() isRepresentation_Representation {
	if x != nil {
		return x.Representation
	}
	return nil
}

func (x *Representation) GetMarkdown() *MarkdownRepresentation {
	if x != nil {
		if x, ok := x.Representation.(*Representation_Markdown); ok {
			return x.Markdown
		}
	}
	return nil
}

func (x *Representation) GetText() *TextRepresentation {
	if x != nil {
		if x, ok := x.Representation.(*Representation_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isRepresentation_Representation interface {
	isRepresentation_Representation()
}

type Representation_Markdown struct {
	Markdown *MarkdownRepresentation `protobuf:"bytes,1,opt,name=markdown,proto3,oneof"`
}

type Representation_Text struct {
	Text *TextRepresentation `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

func (*Representation_Markdown) isRepresentation_Representation() {}

func (*Representation_Text) isRepresentation_Representation() {}

type RecallResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Representations []*Representation      `protobuf:"bytes,1,rep,name=representations,proto3" json:"representations,omitempty"`
	Unavailable     []RepresentationKind   `protobuf:"varint,2,rep,packed,name=unavailable,proto3,enum=corpusrecall.v1.RepresentationKind" json:"unavailable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corpusrecall_v1_recall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_corpusrecall_v1_recall_proto_rawDescGZIP(), []int{4}
}

func (x *RecallResponse) GetRepresentations() []*Representation {
	if x != nil {
		return x.Representations
	}
	return nil
}

func (x *RecallResponse) GetUnavailable() []RepresentationKind {
	if x != nil {
		return x.Unavailable
	}
	return nil
}

var File_corpusrecall_v1_recall_proto protoreflect.FileDescriptor

const file_corpusrecall_v1_recall_proto_rawDesc = "" +
	"\n" +
	"\x1ccorpusrecall/v1/recall.proto\x12\x0fcorpusrecall.v1\"\\\n" +
	"\rRecallRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\x05kinds\x18\x02 \x03(\x0e2#.corpusrecall.v1.RepresentationKindR\x05kinds\"Y\n" +
	"\x16MarkdownRepresentation\x12#\n" +
	"\rcanonical_url\x18\x01 \x01(\tR\fcanonicalUrl\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\"\x7f\n" +
	"\x12TextRepresentation\x12#\n" +
	"\rcanonical_url\x18\x01 \x01(\tR\fcanonicalUrl\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\xa4\x01\n" +
	"\x0eRepresentation\x12E\n" +
	"\bmarkdown\x18\x01 \x01(\v2'.corpusrecall.v1.MarkdownRepresentationH\x00R\bmarkdown\x129\n" +
	"\x04text\x18\x02 \x01(\v2#.corpusrecall.v1.TextRepresentationH\x00R\x04textB\x10\n" +
	"\x0erepresentation\"\xa2\x01\n" +
	"\x0eRecallResponse\x12I\n" +
	"\x0frepresentations\x18\x01 \x03(\v2\x1f.corpusrecall.v1.RepresentationR\x0frepresentations\x12E\n" +
	"\vunavailable\x18\x02 \x03(\x0e2#.corpusrecall.v1.RepresentationKindR\vunavailable*y\n" +
	"\x12RepresentationKind\x12#\n" +
	"\x1fREPRESENTATION_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREPRESENTATION_KIND_MARKDOWN\x10\x01\x12\x1c\n" +
	"\x18REPRESENTATION_KIND_TEXT\x10\x022S\n" +
	"\x06Recall\x12I\n" +
	"\x06Recall\x12\x1e.corpusrecall.v1.RecallRequest\x1a\x1f.corpusrecall.v1.RecallResponseBVZTgithub.com/nikitakarpei/yacy-rwi-node/corpusrecallapi/corpusrecall/v1;corpusrecallv1b\x06proto3"

var (
	file_corpusrecall_v1_recall_proto_rawDescOnce sync.Once
	file_corpusrecall_v1_recall_proto_rawDescData []byte
)

func file_corpusrecall_v1_recall_proto_rawDescGZIP() []byte {
	file_corpusrecall_v1_recall_proto_rawDescOnce.Do(func() {
		file_corpusrecall_v1_recall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corpusrecall_v1_recall_proto_rawDesc), len(file_corpusrecall_v1_recall_proto_rawDesc)))
	})
	return file_corpusrecall_v1_recall_proto_rawDescData
}

var file_corpusrecall_v1_recall_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_corpusrecall_v1_recall_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_corpusrecall_v1_recall_proto_goTypes = []any{
	(RepresentationKind)(0),        // 0: corpusrecall.v1.RepresentationKind
	(*RecallRequest)(nil),          // 1: corpusrecall.v1.RecallRequest
	(*MarkdownRepresentation)(nil), // 2: corpusrecall.v1.MarkdownRepresentation
	(*TextRepresentation)(nil),     // 3: corpusrecall.v1.TextRepresentation
	(*Representation)(nil),         // 4: corpusrecall.v1.Representation
	(*RecallResponse)(nil),         // 5: corpusrecall.v1.RecallResponse
}
var file_corpusrecall_v1_recall_proto_depIdxs = []int32{
	0, // 0: corpusrecall.v1.RecallRequest.kinds:type_name -> corpusrecall.v1.RepresentationKind
	2, // 1: corpusrecall.v1.Representation.markdown:type_name -> corpusrecall.v1.MarkdownRepresentation
	3, // 2: corpusrecall.v1.Representation.text:type_name -> corpusrecall.v1.TextRepresentation
	4, // 3: corpusrecall.v1.RecallResponse.representations:type_name -> corpusrecall.v1.Representation
	0, // 4: corpusrecall.v1.RecallResponse.unavailable:type_name -> corpusrecall.v1.RepresentationKind
	1, // 5: corpusrecall.v1.Recall.Recall:input_type -> corpusrecall.v1.RecallRequest
	5, // 6: corpusrecall.v1.Recall.Recall:output_type -> corpusrecall.v1.RecallResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_corpusrecall_v1_recall_proto_init() }
func file_corpusrecall_v1_recall_proto_init() {
	if File_corpusrecall_v1_recall_proto != nil {
		return
	}
	file_corpusrecall_v1_recall_proto_msgTypes[3].OneofWrappers = []any{
		(*Representation_Markdown)(nil),
		(*Representation_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corpusrecall_v1_recall_proto_rawDesc), len(file_corpusrecall_v1_recall_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corpusrecall_v1_recall_proto_goTypes,
		DependencyIndexes: file_corpusrecall_v1_recall_proto_depIdxs,
		EnumInfos:         file_corpusrecall_v1_recall_proto_enumTypes,
		MessageInfos:      file_corpusrecall_v1_recall_proto_msgTypes,
	}.Build()
	File_corpusrecall_v1_recall_proto = out.File
	file_corpusrecall_v1_recall_proto_goTypes = nil
	file_corpusrecall_v1_recall_proto_depIdxs = nil
}
