name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  e2e:
    needs: verify
    uses: ./.github/workflows/e2e.yml

  build-yacynode:
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-yacynode.yml
    secrets: inherit

  build-yacycrawler:
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-yacycrawler.yml
    secrets: inherit

  build-yacyvisitcrawl:
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-yacyvisitcrawl.yml
    secrets: inherit

  build-yacytextindexer:
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-yacytextindexer.yml
    secrets: inherit

  build-searxng-crawled-text-search:
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-searxng-crawled-text-search.yml
    secrets: inherit

  build-searxng-result-router:
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-searxng-result-router.yml
    secrets: inherit
